# Generated by Django 5.2.3 on 2025-06-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_promocode_emergencycontact_notification_sos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodeuse',
            name='promo_code',
        ),
        migrations.AlterUniqueTogether(
            name='promocodeuse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promocodeuse',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='promocodeuse',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewee',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='sos',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='sos',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.DeleteModel(
            name='PromoCodeUse',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='SOS',
        ),
    ]
