# Generated by Django 5.2.3 on 2025-06-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_promocode_emergencycontact_notification_sos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='driving_quality',
        ),
    ]
