# Generated by Django 5.2.3 on 2025-06-22 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pickup_name', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_name', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('preferred_ride_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('luxury', 'Luxury'), ('shared', 'Shared')], default='standard', max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('use_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', '-last_used'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledRide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('scheduled_datetime', models.DateTimeField()),
                ('recurring_pattern', models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('weekdays', 'Weekdays Only'), ('custom', 'Custom')], default='none', max_length=20)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('ride_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('luxury', 'Luxury'), ('shared', 'Shared')], default='standard', max_length=20)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('advance_booking_time', models.IntegerField(default=15)),
                ('auto_confirm', models.BooleanField(default=True)),
                ('max_wait_time', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('actual_ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ride')),
                ('ride_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ridetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SmartSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('routine', 'Routine Ride'), ('location', 'Popular Destination'), ('time', 'Optimal Time'), ('route', 'Alternative Route'), ('promotion', 'Promotional Offer')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggested_pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_pickup_address', models.TextField(blank=True)),
                ('suggested_destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_destination_address', models.TextField(blank=True)),
                ('suggested_time', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('was_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('favorite', 'Favorite'), ('recent', 'Recent')], default='favorite', max_length=20)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', '-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
