name: rideshare_app
description: "A comprehensive ride sharing mobile application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # HTTP and API
  http: ^1.2.2

  # Local Storage
  shared_preferences: ^2.3.4

  # Maps and Location
  geolocator: ^10.1.1

  # Image handling
  image_picker: ^1.1.2

  # Authentication
  flutter_secure_storage: ^9.2.2

  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
