name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend
        pip install uv
        uv sync
    
    - name: Run Django checks
      run: |
        cd backend
        uv run python manage.py check
    
    - name: Run Django tests
      run: |
        cd backend
        uv run python manage.py test

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
    
    - name: Install dependencies
      run: |
        cd frontend/rideshare_app
        flutter pub get
    
    - name: Analyze Flutter code
      run: |
        cd frontend/rideshare_app
        flutter analyze
    
    - name: Run Flutter tests
      run: |
        cd frontend/rideshare_app
        flutter test
